### ISSUE TITLE
Fail connect port 9200

### ISSUE THREAD

**Issue by glonghi34** [misje/opencti-wazuh-connector#55]
Hello, I apologize for bad writing, I'm from Brazil.
I have this problem that follows in the print.
I tried several adjustments, and it doesn't work.

Your work is fantastic

![image](https://github.com/misje/opencti-wazuh-connector/assets/59581871/7d4989c3-4663-4df6-aa4f-306e2ff0c909)

**Comment by misje** [comment]
Hei,

Can you please verify that your Wazuh installation is reachable from the server running this integration? This message means that Wazuh's OpenSearch server cannot be reached. More specifically, it can reach the IP address, but it appears that OpenSearch isn't running on that port (9200), or possibly not running at all.

**Comment by glonghi34** [comment]
Thank you very much, champ.

Working 100%.

Again, your work is amazing and should be shared.

![image](https://github.com/misje/opencti-wazuh-connector/assets/59581871/cd01c7dd-ac4f-4450-bf15-ccad1f065940)
